trans/urls.py
from django.conf.urls import url

from trans import views


app_name = 'trans'


urlpatterns = [

    url(r'^translate/$', views.translate, name='translate'),

]

trans/forms.py
from django import forms


class TranslateForm(forms.Form):

    text = forms.CharField(max_length=10000, required=True)

    src = forms.CharField(required=True, max_length=2)

    dst = forms.CharField(required=True, max_length=2)

trans/views.py
from django.http.response import HttpResponse, HttpResponseBadRequest

from googletrans import Translator

from trans.forms import TranslateForm


def translate(request):

    translator = Translator()

    form = TranslateForm(request.GET)

    if form.is_valid():

        data = form.cleaned_data

        result = translator.translate(data['text'], data['dst'], data['src'])

        return HttpResponse(result.text)

    return HttpResponseBadRequest('Invalid request')

trans/templates/trans/admin/change_form.html
{% extends 'admin/change_form.html' %}


{% block footer %}
    {{ block.super }}

    {% if trans_options %}
        <script>
            (function ($) {
                var translateUrl = '{% url 'trans:translate' %}',
                    options = {{ trans_options|safe }},
                    $transBtn = $('<button type="button" class="btn btn-primary pull-right"><i class="fa fa-language"></i></button>');

                $.each(options, function (originField, transFields) {

                    var $originField = $('[name=' + originField + ']');

                    $.each(transFields, function (lang, fName) {

                        var $btn = $transBtn.clone(),
                            $field = $('[name=' + fName + ']').css('width', '90%');

                        $field.parent().append($btn);

                        $btn.click(function () {

                            if ($originField.val()) {

                                $btn.prop('disabled', true);
                                $field.prop('disabled', true);

                                var url = translateUrl + '?' + $.param({
                                        text: $originField.val(),
                                        src: '{{ request.LANGUAGE_CODE }}',
                                        dst: lang
                                    });
                                $.get(url, function (result) {
                                    $field.val(result);
                                    $field.prop('disabled', false);
                                    $btn.prop('disabled', false);
                                });

                            }

                        });
                    });
                });

            })(django.jQuery);
        </script>
    {% endif %}
{% endblock %}